# Generated by Django 4.2.26 on 2025-11-24 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sk', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('default_lessons', models.PositiveIntegerField(default=4)),
                ('default_price', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
            ],
        ),
    ]
