# Generated by Django 5.2.8 on 2025-12-07 14:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sk', '0004_add_lesson_feedback_fields'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditlog',
            name='actor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_actions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='debited_from_balance',
            field=models.BooleanField(default=False, help_text='True, если занятие уже списано с баланса'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='link',
            field=models.CharField(blank=True, help_text='Ссылка на урок (Zoom/Discord/и т.п.)', max_length=300),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='scheduled_at',
            field=models.DateTimeField(help_text='Дата и время начала урока'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='status',
            field=models.CharField(choices=[('PLANNED', 'Запланировано'), ('DONE', 'Проведено'), ('CANCELLED', 'Отменено')], default='PLANNED', max_length=20),
        ),
        migrations.AlterField(
            model_name='payment',
            name='confirmed',
            field=models.BooleanField(default=False, help_text='Оплата подтверждена (начислены занятия)'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='package_name',
            field=models.CharField(blank=True, help_text='Название пакета/тарифа', max_length=120),
        ),
    ]
