# Generated by Django migration
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sk', '0008_remove_course_fields'),
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClientRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField(blank=True, help_text='Комментарий клиента (необязательное поле)')),
                ('status', models.CharField(choices=[('SENT', 'Отправлено'), ('RESPONDED', 'Есть реакция на обращение')], default='SENT', help_text='Статус обращения', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('responded_at', models.DateTimeField(blank=True, help_text='Дата и время реакции менеджера', null=True)),
                ('client', models.ForeignKey(help_text='Клиент, который отправил обращение', on_delete=django.db.models.deletion.CASCADE, related_name='client_requests', to='accounts.user')),
                ('manager', models.ForeignKey(blank=True, help_text='Менеджер, который отреагировал на обращение', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='responded_requests', to='accounts.user')),
            ],
            options={
                'verbose_name': 'Обращение клиента',
                'verbose_name_plural': 'Обращения клиентов',
                'ordering': ['-created_at'],
            },
        ),
    ]



