# Generated by Django 5.2.8 on 2025-12-08 01:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sk', '0009_clientrequest'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='course',
            options={'ordering': ['id']},
        ),
    ]
